name: Velocity

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: alpine-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3.2.0

    - name: Build Docker image
      run: docker build -t towinok/velocity:latest .
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: towinok
        password: ${{ secrets.D_TOCKEN }}

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image to GitHub Container Registry
      run: |
        docker push towinok/velocity:latest
